# Generated by Django 5.2.7 on 2026-02-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='has_plate',
            field=models.BooleanField(default=False, verbose_name='دارای پلاک'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='plate_count',
            field=models.IntegerField(default=0, verbose_name='تعداد پلاک'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='plate_data',
            field=models.JSONField(blank=True, null=True, verbose_name='اطلاعات پلاک'),
        ),
    ]
